name: Deploy Laravel App to Hostinger

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the deployment from

jobs:
  deploy:
    name: Deploy Application
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'  # Use the version that matches your Laravel app
          extensions: mbstring, xml, bcmath
          tools: composer

      - name: Install Dependencies
        run: |
          composer install --optimize-autoloader --no-dev
          npm install
          npm run build  # If you're using Vite

      - name: Deploy via SSH
        uses: appleboy/scp-action@v0.1.4
        with:
          host: 45.84.205.136 # ${{ secrets.HOSTINGER_SSH_HOST }}
          username: u992745133 # ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          source: "./"  # Copies the entire Laravel project
          target: ${{ secrets.HOSTINGER_APP_PATH }}  # Path to your subdomain directory
          rm: true  # Remove old files before deploying
          port: 65002 # ${{ secrets.HOSTINGER_SSH_PORT }}

      - name: Run SSH Commands
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: 45.84.205.136 # ${{ secrets.HOSTINGER_SSH_HOST }}
          username: u992745133 # ${{ secrets.HOSTINGER_SSH_USER }}
          key: ${{ secrets.HOSTINGER_SSH_KEY }}
          port: 65002 # ${{ secrets.HOSTINGER_SSH_PORT }}
          script: |
            cd ${{ secrets.HOSTINGER_APP_PATH }}
            composer install --optimize-autoloader --no-dev
            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
            php artisan storage:link
